import localFont from "next/font/local";
import { Press_Start_2P } from "next/font/google";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const press_start_2p = Press_Start_2P({
  subsets: ["cyrillic"],
  display: "swap",
  weight: "400",
  variable: "--font-press_start_2p",
});

export const metadata = {
  title: "Snake Game",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${press_start_2p.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
